import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProvider from "@/components/AppProvider";
import { Box } from "@mui/material";
import MainMenu from "@/components/MainMenu";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            height: "100vh",
            bgcolor: "#f9f9fc",
          }}
        >
          {/* Верхний контент */}
          <Box sx={{ display: "flex", flex: 1 }}>
            {/* Левое меню */}
            <MainMenu />

            {/* Контент */}
            <AppProvider>{children}</AppProvider>
          </Box>

          {/* Footer */}
          <Footer />
        </Box>
      </body>
    </html>
  );
}
